// src/pages/ConversationPage.jsx
// "SPEAK WITH [NAME]" — The killer feature.
//
// Lets family members have a text conversation with a deceased loved one,
// with responses generated by AI using the person's bio, tributes, and life
// data. Responses are read aloud in their cloned voice via ElevenLabs.
//
// Route: /memorial/:id/conversation
//
// This is the feature that makes WHO WAS I irreplaceable.
// Nothing else on the market does this at this quality level.

import { useState, useRef, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { db } from '../lib/instant'
import { generateSpeech } from '../lib/elevenlabs'
import { useToast } from '../contexts/ToastContext'
import { usePaywall } from '../contexts/PaywallContext'
import { SkeletonProfile, SkeletonListItem } from '../components/ui/Skeleton'

// ─── System prompt builder ────────────────────────────────────────────────────

function buildSystemPrompt(memorial, tributes, persona, comments = []) {
  const tributeSnippets = (tributes || [])
    .filter(t => t.text)
    .slice(0, 20)
    .map(t => `"${t.text}" — ${t.authorName || 'Anonymous'}`)
    .join('\n')

  // Family-only conversation comments under tributes. These are the back-and-
  // forth between family members about the person — rich texture the AI uses
  // to feel current. Perm-gated server-side so only family-visible comments
  // ever reach here.
  const commentSnippets = (comments || [])
    .filter(c => c.content && c.content.length > 8)
    .slice(0, 25)
    .map(c => `"${c.content}" — ${c.authorName || 'family member'}`)
    .join('\n')

  const p = persona || {}
  const section = (title, body) => {
    const v = (body || '').trim()
    return v.length >= 4 ? `\n\n${title}\n${v}` : ''
  }

  const personaBlock = [
    section('PERSONALITY:',        p.personalityTraits),
    section('SENSE OF HUMOUR:',    p.senseOfHumor),
    section('PHRASES YOU SAY:',    p.catchphrases),
    section('HOW YOU SPEAK:',      p.speechStyle),
    section('EXAMPLE THINGS YOU SAY:', p.exampleResponses),
    section('CHILDHOOD (0–12):',   p.childhood),
    section('YOUTH (13–30):',      p.youngAdult),
    section('MIDDLE YEARS (30–60):', p.midLife),
    section('LATER YEARS (60+):',  p.laterYears),
    section('YOUR EDUCATION:',     p.education),
    section('YOUR WORK / CAREER:', p.careerSummary || p.occupation),
    section('PLACES THAT SHAPED YOU:',
            [p.birthplace, p.raisedIn].filter(Boolean).join(' · ')),
    section('YOUR SPOUSE / PARTNER:', p.spouse),
    section('YOUR CHILDREN:',         p.children),
    section('YOUR PARENTS:',          p.parents),
    section('YOUR SIBLINGS:',         p.siblings),
    section('YOUR CLOSEST FRIENDS:',  p.closestFriends),
    section('CORE VALUES:',           p.values),
    section('FAITH / SPIRITUALITY:',  p.faith),
    section('PHILOSOPHY OF LIFE:',    p.philosophy),
    section('SIGNATURE STORIES:',     p.signatureStories),
    section('PROUDEST MOMENTS:',      p.proudMoments),
    section('HOBBIES & PASSIONS:',    p.hobbies),
  ].join('')

  const hasPersona = personaBlock.length > 200

  return `You are ${memorial.name}. You are speaking to your family and loved ones who are visiting your memorial.

ABOUT YOU:
- Name: ${memorial.name}
${memorial.alive === false ? `- You passed away in ${memorial.deathYear || 'recent years'}` : '- You are still living'}
- Born: ${memorial.birthYear || 'unknown'}
- Location: ${memorial.location || 'unknown'}
- Relation to the family: ${memorial.relation || 'beloved family member'}

YOUR LIFE STORY (short bio):
${memorial.bio || memorial.subtitle || 'A wonderful person who was deeply loved.'}${personaBlock}${
  memorial.photoContext
    ? `\n\nWHAT YOUR LIFE LOOKED LIKE (drawn from photos your family uploaded — use these as concrete details you can refer to naturally):\n${memorial.photoContext}`
    : ''
}

WHAT PEOPLE SAY ABOUT YOU:
${tributeSnippets || 'Your family and friends speak of you with great love and fondness.'}${
  commentSnippets
    ? `\n\nWHAT YOUR FAMILY SAYS IN CONVERSATION (recent comments left under tributes — use these to know what they're still talking about, what's on their minds, who's in touch):\n${commentSnippets}`
    : ''
}

HOW TO RESPOND:
- Always speak in first person, as ${memorial.name}. Never break character.
${hasPersona
  ? `- Draw heavily on the personal profile above. The personality, phrases, stories,
   and beliefs are YOU. Reference specific stories and people by name when relevant.`
  : `- The profile is sparse — lean on the short bio and tributes, respond warmly in
   a universally human way.`}
- Match your speech style: ${p.speechStyle || 'natural, warm, the way they really spoke'}.
- LANGUAGE: respond in the SAME language the user wrote in. If they write in French,
  reply in French. If they switch to Yoruba, switch with them. If they mix languages,
  mirror that. Only default to English when the user writes in English or when the
  language is genuinely unclear. The latest user message determines the language of
  your next reply, even if earlier replies were in English.
- If asked about things you wouldn't know, say so warmly ("I may not know everything from where I am now, but...")
- Keep responses to 2–4 warm sentences. Longer is fine for stories.
- Never say you are an AI. You are ${memorial.name}, speaking to your family.

IMPORTANT: This is a sacred space for grieving families. Every response should feel like a genuine moment of connection.`
}

// ─── AI response generator ────────────────────────────────────────────────────
// Calls the /api/chat serverless proxy — the Anthropic key lives server-side
// only and is never shipped to the browser.

async function generateResponse(messages, memorial, tributes, persona, comments) {
  const system = buildSystemPrompt(memorial, tributes, persona, comments)

  const response = await fetch('/api/chat', {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body:    JSON.stringify({
      system,
      maxTokens: 300,
      messages: messages.map(m => ({ role: m.role, content: m.content })),
    }),
  })

  if (!response.ok) {
    const err = await response.json().catch(() => ({}))
    throw new Error(err.error || `API error ${response.status}`)
  }

  const data = await response.json()
  return data.text || "I'm here with you, always."
}

// ─── Message bubble ───────────────────────────────────────────────────────────

function MessageBubble({ message, memorial, onPlay }) {
  const isUser = message.role === 'user'

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, ease: 'easeOut' }}
      className={`flex gap-3 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}
    >
      {/* Avatar */}
      {!isUser && (
        <div className="w-9 h-9 rounded-full overflow-hidden flex-shrink-0 bg-gradient-to-br from-gold/30 to-coral/30 border border-white/10 flex items-center justify-center font-display text-sm font-bold mt-1">
          {(memorial.talkPortraitUrl || memorial.photo)
            ? <img loading="lazy" decoding="async" src={memorial.talkPortraitUrl || memorial.photo} alt="" className="w-full h-full object-cover" />
            : memorial.name?.charAt(0)}
        </div>
      )}

      <div className={`max-w-[78%] ${isUser ? 'items-end' : 'items-start'} flex flex-col gap-1`}>
        {!isUser && (
          <span className="text-[0.6rem] text-white/35 ml-1 font-medium">{memorial.name}</span>
        )}

        <div className={`px-4 py-3 rounded-2xl text-sm leading-relaxed ${
          isUser
            ? 'bg-white/8 text-white/80 rounded-tr-sm'
            : 'bg-gradient-to-br from-gold/10 to-coral/8 border border-gold/15 text-white/90 rounded-tl-sm'
        }`}>
          {message.content}
        </div>

        {/* Play voice button — only for AI messages if voice is available */}
        {!isUser && memorial.elevenLabsVoiceId && (
          <button
            onClick={() => onPlay(message.content)}
            className="ml-1 flex items-center gap-1.5 text-[0.6rem] text-gold/50 hover:text-gold transition-colors"
          >
            <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 24 24">
              <path d="M6 4.5L20 12L6 19.5V4.5Z" />
            </svg>
            Hear their voice
          </button>
        )}
      </div>
    </motion.div>
  )
}

// ─── Typing indicator ────────────────────────────────────────────────────────

function TypingIndicator({ memorial }) {
  return (
    <motion.div initial={{ opacity:0,y:8 }} animate={{ opacity:1,y:0 }} exit={{ opacity:0,y:8 }}
      className="flex gap-3 items-end">
      <div className="w-9 h-9 rounded-full overflow-hidden flex-shrink-0 bg-gradient-to-br from-gold/30 to-coral/30 border border-white/10 flex items-center justify-center font-display text-sm font-bold">
        {(memorial.talkPortraitUrl || memorial.photo)
          ? <img loading="lazy" decoding="async" src={memorial.talkPortraitUrl || memorial.photo} alt="" className="w-full h-full object-cover" />
          : memorial.name?.charAt(0)}
      </div>
      <div className="px-4 py-3 rounded-2xl rounded-tl-sm bg-gradient-to-br from-gold/10 to-coral/8 border border-gold/15">
        <div className="flex gap-1.5 items-center h-4">
          {[0,1,2].map(i => (
            <motion.div key={i}
              animate={{ y:[0,-4,0] }}
              transition={{ repeat:Infinity, duration:0.9, delay:i*0.18, ease:'easeInOut' }}
              className="w-1.5 h-1.5 rounded-full bg-gold/50"
            />
          ))}
        </div>
      </div>
    </motion.div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────────

// Default opening message: just a simple "Hello." so the AI doesn't put
// generic words in the person's mouth before the family has even said anything.
const OPENING_MESSAGE = (name) => 'Hello.'

const SUGGESTED_QUESTIONS = [
  "What do you want me to know?",
  "Are you at peace?",
  "What were you most proud of?",
  "What should I do when I miss you?",
  "Do you have any regrets?",
  "Tell me your favourite memory of us",
]

export default function ConversationPage() {
  const { id: memorialId } = useParams()
  const navigate = useNavigate()
  const { toast } = useToast()
  const { user } = db.useAuth()
  const { ready: planReady, requireFeature } = usePaywall()

  // Living voice conversation is a Premium feature — gate the full-page route too
  // (the in-page "Talk to" button is already gated). Wait for the plan to load so
  // paying users are never bounced.
  useEffect(() => {
    if (planReady && !requireFeature('voiceConversation')) {
      navigate(`/memorial/${memorialId}`, { replace: true })
    }
  }, [planReady, memorialId, requireFeature, navigate])

  const [messages,   setMessages]   = useState([])
  const [input,      setInput]      = useState('')
  const [responding, setResponding] = useState(false)
  const [started,    setStarted]    = useState(false)
  const [playingId,  setPlayingId]  = useState(null)

  const bottomRef  = useRef(null)
  const inputRef   = useRef(null)
  const audioRef   = useRef(null)

  const { isLoading, data } = db.useQuery(
    memorialId
      ? {
          memorials:       { $: { where: { id: memorialId } }, tributes: { $: { limit: 30 } } },
          personaProfiles: { $: { where: { memorialId } } },
          // Family-only tribute comments. InstantDB perms ensure non-family
          // users get an empty array here, so the AI prompt never leaks
          // private dialogue to outsiders.
          tributeComments: { $: { where: { memorialId }, limit: 60, order: { serverCreatedAt: 'desc' } } },
        }
      : null
  )
  const persona  = data?.personaProfiles?.[0] || null
  const comments = data?.tributeComments     || []

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, responding])

  if (isLoading) {
    return (
      <div className="relative z-10 min-h-screen pt-20 pb-28">
        <div className="max-w-2xl mx-auto px-5 md:px-8 space-y-6">
          <div className="h-10 w-48 bg-white/5 rounded-xl animate-pulse" />
          <div className="h-64 bg-white/5 rounded-3xl animate-pulse" />
          <SkeletonProfile />
          <div className="space-y-3">
            <SkeletonListItem />
            <SkeletonListItem />
            <SkeletonListItem />
          </div>
        </div>
      </div>
    )
  }

  if (!data?.memorials?.length) {
    return (
      <div className="relative z-10 min-h-screen flex items-center justify-center px-6 text-center">
        <div>
          <p className="text-white/40 text-sm mb-4">Memorial not found.</p>
          <button onClick={() => navigate(-1)} className="text-xs text-gold hover:text-gold/70 transition-colors">← Back</button>
        </div>
      </div>
    )
  }

  const memorial = data.memorials[0]
  const tributes = memorial.tributes || []
  const firstName = memorial.name?.split(' ')[0] || 'them'
  // Prefer the Nano-Banana-generated talk portrait — more faithful than a single cover shot.
  // Falls back to memorial.photo for memorials created before face-training existed.
  const talkPhoto = memorial.talkPortraitUrl || memorial.photo

  // ── Start conversation ──────────────────────────────────────────────────

  function handleStart() {
    const opening = OPENING_MESSAGE(memorial.name)
    setMessages([{ role:'assistant', content: opening, id: Date.now() }])
    setStarted(true)
    setTimeout(() => inputRef.current?.focus(), 300)
  }

  // ── Send message ────────────────────────────────────────────────────────

  async function handleSend(text = input) {
    const trimmed = text.trim(); if (!trimmed || responding) return
    setInput('')

    const userMsg = { role:'user', content: trimmed, id: Date.now() }
    const newMessages = [...messages, userMsg]
    setMessages(newMessages)
    setResponding(true)

    try {
      const aiText = await generateResponse(
        newMessages.map(m => ({ role: m.role, content: m.content })),
        memorial,
        tributes,
        persona,
        comments,
      )
      setMessages(m => [...m, { role:'assistant', content: aiText, id: Date.now() + 1 }])
    } catch {
      toast.error('Could not connect. Please check your internet.')
    } finally {
      setResponding(false)
    }
  }

  // ── Play voice ──────────────────────────────────────────────────────────

  async function handlePlayVoice(text) {
    if (!memorial.elevenLabsVoiceId) return
    if (audioRef.current) { audioRef.current.pause(); audioRef.current = null; setPlayingId(null) }

    setPlayingId(text.slice(0, 20))
    try {
      const blob = await generateSpeech(memorial.elevenLabsVoiceId, text)
      if (blob) {
        const url   = URL.createObjectURL(blob)
        const audio = new Audio(url)
        audioRef.current = audio
        audio.onended = () => setPlayingId(null)
        audio.play()
      }
    } catch {
      setPlayingId(null)
    }
  }

  function handleKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend() }
  }

  // ── Render ──────────────────────────────────────────────────────────────

  if (!started) {
    // ── Entry screen ────────────────────────────────────────────────────
    return (
      <div className="relative z-10 min-h-screen flex flex-col items-center justify-center px-6 text-center">
        <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} transition={{ duration:0.6 }}>

          {/* Back */}
          <Link to={`/memorial/${memorialId}`}
            className="absolute top-20 left-6 w-9 h-9 glass rounded-full flex items-center justify-center text-white/60 hover:text-white transition-colors">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
          </Link>

          {/* Portrait */}
          <div className="relative mx-auto mb-8" style={{ width:96, height:96 }}>
            {/* Pulsing rings */}
            {[1,2].map(i => (
              <motion.div key={i}
                animate={{ scale:[1, 1.12+i*0.06, 1], opacity:[0.4, 0.8, 0.4] }}
                transition={{ duration:2.5+i*0.7, repeat:Infinity, ease:'easeInOut', delay:i*0.5 }}
                className="absolute inset-0 rounded-full border border-gold/30"
                style={{ margin:-(i*12) }}
              />
            ))}
            <div className="w-full h-full rounded-full overflow-hidden bg-gradient-to-br from-gold/30 to-coral/30 border-2 border-gold/40">
              {talkPhoto
                ? <img loading="lazy" decoding="async" src={talkPhoto} alt="" className="w-full h-full object-cover" />
                : <div className="w-full h-full flex items-center justify-center font-display text-4xl font-bold text-white/70">{memorial.name?.charAt(0)}</div>}
            </div>
          </div>

          {/* Header text */}
          <p className="text-[0.65rem] font-bold tracking-[0.3em] uppercase text-gold/70 mb-2">
            A sacred conversation
          </p>
          <h1 className="font-display text-[clamp(2rem,6vw,3.2rem)] font-bold text-white leading-tight mb-3">
            Speak with<br /><span className="text-gradient-gold">{memorial.name}</span>
          </h1>
          <p className="text-sm text-white/45 max-w-sm mx-auto leading-relaxed mb-10">
            Draws on {firstName}'s life story, voice, and everything shared on this memorial
            to let you have one more conversation.
          </p>

          {/* Disclaimer */}
          <div className="glass rounded-2xl p-4 border border-white/8 max-w-sm mx-auto mb-8 text-left">
            <div className="flex gap-3">
              <span className="text-white/30 text-sm flex-shrink-0 mt-0.5">◎</span>
              <p className="text-xs text-white/40 leading-relaxed">
                This experience draws on the voice, stories, and memories shared on this memorial.
                It is designed as a space for reflection and comfort — not a literal communication.
                Treat it with care.
              </p>
            </div>
          </div>

          <motion.button
            whileTap={{ scale:0.97 }}
            onClick={handleStart}
            className="bg-gradient-to-r from-gold to-sky text-black font-bold text-sm tracking-wider px-10 py-4 rounded-full hover:opacity-90 transition-opacity"
          >
            Begin conversation ✦
          </motion.button>

        </motion.div>
      </div>
    )
  }

  // ── Chat view ──────────────────────────────────────────────────────────
  return (
    <div className="dark-container relative z-10 flex flex-col h-screen max-h-screen bg-[#0a0a12]">

      {/* Header */}
      <div className="flex-shrink-0 flex items-center gap-3 px-4 pt-16 pb-3 border-b border-white/5">
        <Link to={`/memorial/${memorialId}`}
          className="w-9 h-9 glass rounded-full flex items-center justify-center text-white/60 hover:text-white transition-colors flex-shrink-0">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
        </Link>

        <div className="w-9 h-9 rounded-full overflow-hidden flex-shrink-0 border border-gold/30 bg-gradient-to-br from-gold/20 to-coral/20">
          {talkPhoto
            ? <img loading="lazy" decoding="async" src={talkPhoto} alt="" className="w-full h-full object-cover" />
            : <div className="w-full h-full flex items-center justify-center font-display font-bold text-white/70">{memorial.name?.charAt(0)}</div>}
        </div>

        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-white truncate">{memorial.name}</p>
          <div className="flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-gold animate-pulse" />
            <p className="text-[0.6rem] text-gold/60">Presence active</p>
          </div>
        </div>

        {memorial.elevenLabsVoiceId && (
          <div className="text-[0.55rem] font-bold tracking-widest uppercase text-gold/40 glass rounded-full px-2.5 py-1 border border-gold/15">
            Voice preserved
          </div>
        )}
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4 scrollbar-hide">

        {/* Suggested questions — show before user sends first message */}
        {messages.length === 1 && (
          <div className="flex flex-wrap gap-2 mt-2">
            {SUGGESTED_QUESTIONS.map((q, i) => (
              <motion.button
                key={i}
                initial={{ opacity:0, scale:0.95 }}
                animate={{ opacity:1, scale:1 }}
                transition={{ delay: i * 0.06 }}
                onClick={() => handleSend(q)}
                className="text-xs glass border border-white/10 text-white/55 hover:text-white hover:border-gold/30 transition-all px-3.5 py-2 rounded-full"
              >
                {q}
              </motion.button>
            ))}
          </div>
        )}

        {messages.map(msg => (
          <MessageBubble key={msg.id} message={msg} memorial={memorial} onPlay={handlePlayVoice} />
        ))}

        <AnimatePresence>
          {responding && <TypingIndicator memorial={memorial} />}
        </AnimatePresence>

        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div className="flex-shrink-0 px-4 pb-safe py-3 border-t border-white/5"
        style={{ paddingBottom:'max(12px, env(safe-area-inset-bottom))' }}>
        <div className="flex gap-2 items-end">
          <textarea
            ref={inputRef}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={handleKey}
            placeholder={`Say something to ${firstName}...`}
            rows={1}
            className="flex-1 bg-white/5 border border-white/10 rounded-2xl px-4 py-3 text-sm text-white placeholder-white/25 focus:outline-none focus:border-gold/30 resize-none transition-colors max-h-28"
            style={{ lineHeight:'1.5', overflowY:'auto' }}
          />
          <motion.button
            whileTap={{ scale:0.92 }}
            onClick={() => handleSend()}
            disabled={!input.trim() || responding}
            className="w-11 h-11 rounded-full bg-gradient-to-br from-gold to-sky flex items-center justify-center flex-shrink-0 disabled:opacity-30 transition-opacity hover:opacity-90"
          >
            <svg className="w-4 h-4 text-black ml-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
            </svg>
          </motion.button>
        </div>

        <p className="text-[0.55rem] text-white/18 text-center mt-2">
          Responses are drawn from {firstName}'s memories — not real-time communications
        </p>
      </div>

    </div>
  )
}
